import { plantillaBase, type PackVertical } from './tipos';

export const packAutomotriz: PackVertical = {
  codigo: 'AUTOMOTRIZ',
  nombre: 'Automotriz',
  usaAplicaciones: false,
  unidadesMedida: [
    { codigo: 'UND', nombre: 'Unidad', permiteDecimales: false },
    { codigo: 'SERV', nombre: 'Servicio', permiteDecimales: false },
  ],
  definicionesAtributo: [
    {
      codigo: 'vin',
      etiqueta: 'VIN',
      tipoDato: 'TEXTO',
      requerido: true,
      usarEnBusqueda: true,
      orden: 1,
    },
    {
      codigo: 'anio',
      etiqueta: 'Año',
      tipoDato: 'ENTERO',
      requerido: false,
      usarEnBusqueda: true,
      orden: 2,
    },
    {
      codigo: 'kilometraje',
      etiqueta: 'Kilometraje',
      tipoDato: 'ENTERO',
      unidadSugerida: 'KM',
      requerido: false,
      usarEnBusqueda: false,
      orden: 3,
    },
    {
      codigo: 'transmision',
      etiqueta: 'Transmision',
      tipoDato: 'LISTA',
      opciones: ['AUTOMATICA', 'SINCRONICA'],
      requerido: false,
      usarEnBusqueda: false,
      orden: 4,
    },
    {
      codigo: 'combustible',
      etiqueta: 'Combustible',
      tipoDato: 'LISTA',
      opciones: ['GASOLINA', 'DIESEL', 'GAS', 'HIBRIDO', 'ELECTRICO'],
      requerido: false,
      usarEnBusqueda: false,
      orden: 5,
    },
    {
      codigo: 'traccion',
      etiqueta: 'Traccion',
      tipoDato: 'LISTA',
      opciones: ['4X2', '4X4', 'AWD'],
      requerido: false,
      usarEnBusqueda: false,
      orden: 6,
    },
    {
      codigo: 'color',
      etiqueta: 'Color',
      tipoDato: 'TEXTO',
      requerido: false,
      usarEnBusqueda: false,
      orden: 7,
    },
    {
      codigo: 'condicion',
      etiqueta: 'Condicion',
      tipoDato: 'LISTA',
      opciones: ['NUEVO', 'USADO'],
      requerido: false,
      usarEnBusqueda: false,
      orden: 8,
    },
  ],
  categorias: [
    {
      nombre: 'Vehiculos nuevos',
      orden: 1,
      subcategorias: [
        { nombre: 'Sedan', orden: 1 },
        { nombre: 'SUV y camioneta', orden: 2 },
        { nombre: 'Pick-up', orden: 3 },
        { nombre: 'Comercial', orden: 4 },
      ],
    },
    {
      nombre: 'Vehiculos usados',
      orden: 2,
      subcategorias: [
        { nombre: 'Sedan', orden: 1 },
        { nombre: 'SUV y camioneta', orden: 2 },
        { nombre: 'Pick-up', orden: 3 },
        { nombre: 'Comercial', orden: 4 },
      ],
    },
    {
      nombre: 'Accesorios',
      orden: 3,
      subcategorias: [
        { nombre: 'Seguridad', orden: 1 },
        { nombre: 'Confort', orden: 2 },
        { nombre: 'Estetica', orden: 3 },
      ],
    },
    {
      nombre: 'Servicios',
      orden: 4,
      subcategorias: [
        { nombre: 'Gestion documental', orden: 1 },
        { nombre: 'Traspaso', orden: 2 },
        { nombre: 'Preparacion y entrega', orden: 3 },
      ],
    },
  ],
  sinonimos: [
    { texto: 'carro nuevo', destinoTipo: 'CATEGORIA', destino: 'Vehiculos nuevos' },
    { texto: 'camioneta', destinoTipo: 'CATEGORIA', destino: 'SUV y camioneta' },
    { texto: 'automatico', destinoTipo: 'TERMINO', destino: 'transmision automatica' },
    { texto: 'sincronico', destinoTipo: 'TERMINO', destino: 'transmision sincronica' },
    { texto: '4x4', destinoTipo: 'TERMINO', destino: 'traccion 4X4' },
    { texto: 'full equipo', destinoTipo: 'TERMINO', destino: 'equipamiento completo' },
    { texto: 'papeles al dia', destinoTipo: 'CATEGORIA', destino: 'Gestion documental' },
  ],
  configuracionCotizacion: {
    vigenciaHorasPredeterminada: 168,
    aplicaImpuesto: true,
    porcentajeImpuesto: '16.0000',
    preciosIncluyenImpuesto: false,
    decimalesRedondeo: 2,
    modoRedondeo: 'NORMAL',
    mostrarDescuentoDetallado: false,
    permiteSobrescribirPrecio: true,
  },
  plantillaDocumento: plantillaBase(
    [
      { campo: 'ORDEN', etiqueta: '#', orden: 1 },
      { campo: 'DESCRIPCION', etiqueta: 'Vehiculo', orden: 2 },
      { campo: 'ATRIBUTO', etiqueta: 'VIN', atributoCodigo: 'vin', orden: 3 },
      { campo: 'ATRIBUTO', etiqueta: 'Año', atributoCodigo: 'anio', orden: 4 },
      { campo: 'CANTIDAD', etiqueta: 'Cant.', orden: 5 },
      { campo: 'PRECIO_UNITARIO', etiqueta: 'Precio', orden: 6 },
      { campo: 'TOTAL_LINEA', etiqueta: 'Total', orden: 7 },
    ],
    { mostrarImpuesto: true, mostrarDescuento: false },
  ),
};
