import { plantillaBase, type PackVertical } from './tipos';

export const packFerreteria: PackVertical = {
  codigo: 'FERRETERIA',
  nombre: 'Ferretería',
  usaAplicaciones: false,
  unidadesMedida: [
    { codigo: 'UND', nombre: 'Unidad', permiteDecimales: false },
    { codigo: 'M', nombre: 'Metro', permiteDecimales: true },
    { codigo: 'KG', nombre: 'Kilogramo', permiteDecimales: true },
    { codigo: 'CAJA', nombre: 'Caja', permiteDecimales: false },
    { codigo: 'SACO', nombre: 'Saco', permiteDecimales: false },
    { codigo: 'LT', nombre: 'Litro', permiteDecimales: true },
    { codigo: 'JGO', nombre: 'Juego', permiteDecimales: false },
    { codigo: 'ROLLO', nombre: 'Rollo', permiteDecimales: false },
  ],
  definicionesAtributo: [
    {
      codigo: 'diametro',
      etiqueta: 'Diametro',
      tipoDato: 'TEXTO',
      requerido: false,
      usarEnBusqueda: true,
      orden: 1,
    },
    {
      codigo: 'material',
      etiqueta: 'Material',
      tipoDato: 'LISTA',
      opciones: ['PVC', 'CPVC', 'HG', 'COBRE', 'PPR', 'ACERO', 'ALUMINIO', 'PLASTICO'],
      requerido: false,
      usarEnBusqueda: true,
      orden: 2,
    },
    {
      codigo: 'medida',
      etiqueta: 'Medida',
      tipoDato: 'TEXTO',
      requerido: false,
      usarEnBusqueda: true,
      orden: 3,
    },
    {
      codigo: 'presentacion',
      etiqueta: 'Presentacion',
      tipoDato: 'TEXTO',
      requerido: false,
      usarEnBusqueda: false,
      orden: 4,
    },
    {
      codigo: 'color',
      etiqueta: 'Color',
      tipoDato: 'TEXTO',
      requerido: false,
      usarEnBusqueda: false,
      orden: 5,
    },
    {
      codigo: 'rosca',
      etiqueta: 'Rosca',
      tipoDato: 'LISTA',
      opciones: ['SIN_ROSCA', 'NPT', 'BSP', 'MACHO', 'HEMBRA'],
      requerido: false,
      usarEnBusqueda: false,
      orden: 6,
    },
  ],
  categorias: [
    {
      nombre: 'Plomeria',
      orden: 1,
      subcategorias: [
        { nombre: 'Tuberia', orden: 1 },
        { nombre: 'Conexiones', orden: 2 },
        { nombre: 'Llaves y valvulas', orden: 3 },
        { nombre: 'Griferia', orden: 4 },
        { nombre: 'Sanitarios', orden: 5 },
      ],
    },
    {
      nombre: 'Electricidad',
      orden: 2,
      subcategorias: [
        { nombre: 'Cables', orden: 1 },
        { nombre: 'Tomacorrientes e interruptores', orden: 2 },
        { nombre: 'Iluminacion', orden: 3 },
        { nombre: 'Tuberia y canalizacion', orden: 4 },
        { nombre: 'Tableros y breakers', orden: 5 },
      ],
    },
    {
      nombre: 'Herramientas',
      orden: 3,
      subcategorias: [
        { nombre: 'Manuales', orden: 1 },
        { nombre: 'Electricas', orden: 2 },
        { nombre: 'Medicion', orden: 3 },
        { nombre: 'Accesorios y brocas', orden: 4 },
      ],
    },
    {
      nombre: 'Pinturas',
      orden: 4,
      subcategorias: [
        { nombre: 'Pintura de caucho', orden: 1 },
        { nombre: 'Esmaltes', orden: 2 },
        { nombre: 'Fondos y bases', orden: 3 },
        { nombre: 'Solventes', orden: 4 },
        { nombre: 'Accesorios de pintura', orden: 5 },
      ],
    },
    {
      nombre: 'Ferreteria general',
      orden: 5,
      subcategorias: [
        { nombre: 'Candados y cerraduras', orden: 1 },
        { nombre: 'Cadenas y guayas', orden: 2 },
        { nombre: 'Herrajes', orden: 3 },
        { nombre: 'Articulos de limpieza', orden: 4 },
      ],
    },
    {
      nombre: 'Construccion',
      orden: 6,
      subcategorias: [
        { nombre: 'Cemento y agregados', orden: 1 },
        { nombre: 'Bloques y ladrillos', orden: 2 },
        { nombre: 'Acero de refuerzo', orden: 3 },
        { nombre: 'Impermeabilizantes', orden: 4 },
      ],
    },
    {
      nombre: 'Adhesivos y sellantes',
      orden: 7,
      subcategorias: [
        { nombre: 'Pegamentos', orden: 1 },
        { nombre: 'Siliconas', orden: 2 },
        { nombre: 'Cintas', orden: 3 },
        { nombre: 'Masillas', orden: 4 },
      ],
    },
    {
      nombre: 'Tornilleria',
      orden: 8,
      subcategorias: [
        { nombre: 'Tornillos', orden: 1 },
        { nombre: 'Tuercas y arandelas', orden: 2 },
        { nombre: 'Clavos', orden: 3 },
        { nombre: 'Anclajes y ramplugs', orden: 4 },
      ],
    },
  ],
  sinonimos: [
    { texto: 'tubo de media', destinoTipo: 'TERMINO', destino: 'tubo 1/2"' },
    { texto: 'pega azul', destinoTipo: 'TERMINO', destino: 'pegamento PVC' },
    { texto: 'cinta de plomero', destinoTipo: 'TERMINO', destino: 'teflon' },
    { texto: 'cable numero 12', destinoTipo: 'TERMINO', destino: 'cable 12 AWG' },
    { texto: 'chaza', destinoTipo: 'TERMINO', destino: 'ramplug' },
    { texto: 'bombillo', destinoTipo: 'CATEGORIA', destino: 'Iluminacion' },
    { texto: 'manguera', destinoTipo: 'CATEGORIA', destino: 'Tuberia' },
    { texto: 'tirro', destinoTipo: 'TERMINO', destino: 'cinta adhesiva de papel' },
    { texto: 'pintura de caucho', destinoTipo: 'CATEGORIA', destino: 'Pintura de caucho' },
    { texto: 'varilla', destinoTipo: 'TERMINO', destino: 'cabilla' },
  ],
  configuracionCotizacion: {
    vigenciaHorasPredeterminada: 48,
    aplicaImpuesto: false,
    porcentajeImpuesto: '0.0000',
    preciosIncluyenImpuesto: false,
    decimalesRedondeo: 2,
    modoRedondeo: 'NORMAL',
    mostrarDescuentoDetallado: true,
    permiteSobrescribirPrecio: true,
  },
  plantillaDocumento: plantillaBase([
    { campo: 'ORDEN', etiqueta: '#', orden: 1 },
    { campo: 'DESCRIPCION', etiqueta: 'Descripcion', orden: 2 },
    { campo: 'UNIDAD', etiqueta: 'Unidad', orden: 3 },
    { campo: 'CANTIDAD', etiqueta: 'Cant.', orden: 4 },
    { campo: 'PRECIO_UNITARIO', etiqueta: 'Precio', orden: 5 },
    { campo: 'TOTAL_LINEA', etiqueta: 'Total', orden: 6 },
    {
      campo: 'ATRIBUTO',
      etiqueta: 'Presentacion',
      atributoCodigo: 'presentacion',
      orden: 7,
      visible: true,
    },
  ]),
};
