import { plantillaBase, type PackVertical } from './tipos';

export const packRepuestos: PackVertical = {
  codigo: 'REPUESTOS',
  nombre: 'Repuestos',
  usaAplicaciones: true,
  unidadesMedida: [
    { codigo: 'UND', nombre: 'Unidad', permiteDecimales: false },
    { codigo: 'JGO', nombre: 'Juego', permiteDecimales: false },
    { codigo: 'PAR', nombre: 'Par', permiteDecimales: false },
    { codigo: 'LT', nombre: 'Litro', permiteDecimales: true },
    { codigo: 'KIT', nombre: 'Kit', permiteDecimales: false },
  ],
  definicionesAtributo: [
    {
      codigo: 'numeroParte',
      etiqueta: 'Numero de parte',
      tipoDato: 'TEXTO',
      requerido: false,
      usarEnBusqueda: true,
      orden: 1,
    },
    {
      codigo: 'posicion',
      etiqueta: 'Posicion',
      tipoDato: 'LISTA',
      opciones: ['DELANTERA', 'TRASERA', 'IZQUIERDA', 'DERECHA', 'SUPERIOR', 'INFERIOR'],
      requerido: false,
      usarEnBusqueda: true,
      orden: 2,
    },
    {
      codigo: 'lado',
      etiqueta: 'Lado',
      tipoDato: 'LISTA',
      opciones: ['IZQUIERDO', 'DERECHO', 'AMBOS'],
      requerido: false,
      usarEnBusqueda: false,
      orden: 3,
    },
    {
      codigo: 'sistema',
      etiqueta: 'Sistema',
      tipoDato: 'LISTA',
      opciones: [
        'FRENOS',
        'SUSPENSION',
        'MOTOR',
        'TRANSMISION',
        'ELECTRICO',
        'ENFRIAMIENTO',
        'CARROCERIA',
      ],
      requerido: false,
      usarEnBusqueda: true,
      orden: 4,
    },
    {
      codigo: 'origen',
      etiqueta: 'Origen',
      tipoDato: 'LISTA',
      opciones: ['ORIGINAL', 'ALTERNO', 'GENUINO'],
      requerido: false,
      usarEnBusqueda: false,
      orden: 5,
    },
  ],
  categorias: [
    {
      nombre: 'Frenos',
      orden: 1,
      subcategorias: [
        { nombre: 'Pastillas', orden: 1 },
        { nombre: 'Discos y tambores', orden: 2 },
        { nombre: 'Bombas y cilindros', orden: 3 },
        { nombre: 'Mangueras y liquido', orden: 4 },
      ],
    },
    {
      nombre: 'Suspension y direccion',
      orden: 2,
      subcategorias: [
        { nombre: 'Amortiguadores', orden: 1 },
        { nombre: 'Rotulas y terminales', orden: 2 },
        { nombre: 'Bujes y cauchos', orden: 3 },
        { nombre: 'Rolineras', orden: 4 },
      ],
    },
    {
      nombre: 'Motor',
      orden: 3,
      subcategorias: [
        { nombre: 'Empacaduras', orden: 1 },
        { nombre: 'Correas y tensores', orden: 2 },
        { nombre: 'Bombas', orden: 3 },
        { nombre: 'Sensores', orden: 4 },
        { nombre: 'Sistema de encendido', orden: 5 },
      ],
    },
    {
      nombre: 'Transmision',
      orden: 4,
      subcategorias: [
        { nombre: 'Embrague', orden: 1 },
        { nombre: 'Cajas y sincronicos', orden: 2 },
        { nombre: 'Juntas homocineticas', orden: 3 },
        { nombre: 'Aceites de caja', orden: 4 },
      ],
    },
    {
      nombre: 'Sistema electrico',
      orden: 5,
      subcategorias: [
        { nombre: 'Baterias', orden: 1 },
        { nombre: 'Alternadores y arranques', orden: 2 },
        { nombre: 'Iluminacion', orden: 3 },
        { nombre: 'Cableado y fusibles', orden: 4 },
      ],
    },
    {
      nombre: 'Enfriamiento',
      orden: 6,
      subcategorias: [
        { nombre: 'Radiadores', orden: 1 },
        { nombre: 'Termostatos', orden: 2 },
        { nombre: 'Ventiladores', orden: 3 },
        { nombre: 'Mangueras y refrigerante', orden: 4 },
      ],
    },
    {
      nombre: 'Carroceria',
      orden: 7,
      subcategorias: [
        { nombre: 'Parachoques', orden: 1 },
        { nombre: 'Faros y luces', orden: 2 },
        { nombre: 'Espejos', orden: 3 },
        { nombre: 'Vidrios y molduras', orden: 4 },
      ],
    },
    {
      nombre: 'Filtros y lubricantes',
      orden: 8,
      subcategorias: [
        { nombre: 'Filtros de aceite', orden: 1 },
        { nombre: 'Filtros de aire', orden: 2 },
        { nombre: 'Filtros de combustible', orden: 3 },
        { nombre: 'Aceites y aditivos', orden: 4 },
      ],
    },
  ],
  sinonimos: [
    { texto: 'pastillas', destinoTipo: 'TERMINO', destino: 'pastillas de freno' },
    { texto: 'bomba de agua', destinoTipo: 'TERMINO', destino: 'bomba de agua' },
    { texto: 'tren delantero', destinoTipo: 'CATEGORIA', destino: 'Suspension y direccion' },
    { texto: 'sincronico', destinoTipo: 'TERMINO', destino: 'embrague' },
    { texto: 'caucho de suspension', destinoTipo: 'TERMINO', destino: 'buje de suspension' },
    { texto: 'rolinera', destinoTipo: 'TERMINO', destino: 'rodamiento' },
    { texto: 'bujia', destinoTipo: 'CATEGORIA', destino: 'Sistema de encendido' },
    { texto: 'correa de tiempo', destinoTipo: 'TERMINO', destino: 'correa de distribucion' },
    { texto: 'guaya de freno', destinoTipo: 'TERMINO', destino: 'cable de freno de mano' },
  ],
  configuracionCotizacion: {
    vigenciaHorasPredeterminada: 72,
    aplicaImpuesto: false,
    porcentajeImpuesto: '0.0000',
    preciosIncluyenImpuesto: false,
    decimalesRedondeo: 2,
    modoRedondeo: 'NORMAL',
    mostrarDescuentoDetallado: true,
    permiteSobrescribirPrecio: true,
  },
  plantillaDocumento: plantillaBase([
    { campo: 'ORDEN', etiqueta: '#', orden: 1 },
    { campo: 'SKU', etiqueta: 'Codigo', orden: 2 },
    { campo: 'DESCRIPCION', etiqueta: 'Repuesto', orden: 3 },
    { campo: 'MARCA', etiqueta: 'Marca', orden: 4 },
    {
      campo: 'ATRIBUTO',
      etiqueta: 'N. parte',
      atributoCodigo: 'numeroParte',
      orden: 5,
    },
    { campo: 'CANTIDAD', etiqueta: 'Cant.', orden: 6 },
    { campo: 'PRECIO_UNITARIO', etiqueta: 'Precio', orden: 7 },
    { campo: 'TOTAL_LINEA', etiqueta: 'Total', orden: 8 },
  ]),
};
