export enum EstadoRegistro {
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
}

export enum AmbitoPerfil {
  PLATAFORMA = 'PLATAFORMA',
  ORGANIZACION = 'ORGANIZACION',
}

export enum TipoDatoAtributo {
  TEXTO = 'TEXTO',
  NUMERO = 'NUMERO',
  ENTERO = 'ENTERO',
  BOOLEANO = 'BOOLEANO',
  LISTA = 'LISTA',
  RANGO_ANIO = 'RANGO_ANIO',
}

export enum ModoRedondeo {
  NORMAL = 'NORMAL',
  ARRIBA = 'ARRIBA',
  ABAJO = 'ABAJO',
}

export enum TipoItem {
  FUNGIBLE = 'FUNGIBLE',
  SERIALIZADO = 'SERIALIZADO',
  SERVICIO = 'SERVICIO',
}

export enum OrigenAlias {
  MANUAL = 'MANUAL',
  IMPORTADO = 'IMPORTADO',
  APRENDIDO = 'APRENDIDO',
}

export enum TipoImportacion {
  ITEMS = 'ITEMS',
  PRECIOS = 'PRECIOS',
  ALIAS = 'ALIAS',
}

export enum EstadoImportacion {
  CARGADA = 'CARGADA',
  VALIDADA = 'VALIDADA',
  CONFIRMADA = 'CONFIRMADA',
  FALLIDA = 'FALLIDA',
  CANCELADA = 'CANCELADA',
}

export enum AmbitoReglaDescuento {
  ITEM = 'ITEM',
  CATEGORIA = 'CATEGORIA',
  MARCA = 'MARCA',
  GLOBAL = 'GLOBAL',
}

export enum TipoDescuento {
  PORCENTAJE = 'PORCENTAJE',
  MONTO_FIJO = 'MONTO_FIJO',
  PRECIO_FIJO = 'PRECIO_FIJO',
}

export enum FuenteTasaCambio {
  MANUAL = 'MANUAL',
  AUTOMATICA = 'AUTOMATICA',
}

export enum CanalSolicitud {
  WHATSAPP_PEGADO = 'WHATSAPP_PEGADO',
  MANUAL = 'MANUAL',
  API = 'API',
}

export enum EstadoSolicitud {
  PENDIENTE = 'PENDIENTE',
  INTERPRETADA = 'INTERPRETADA',
  FALLIDA = 'FALLIDA',
}

export enum EstadoCotizacion {
  BORRADOR = 'BORRADOR',
  APROBADA = 'APROBADA',
  ENVIADA = 'ENVIADA',
  GANADA = 'GANADA',
  PERDIDA = 'PERDIDA',
  VENCIDA = 'VENCIDA',
  ANULADA = 'ANULADA',
}

export enum EstadoResolucionLinea {
  RESUELTA_AUTOMATICA = 'RESUELTA_AUTOMATICA',
  RESUELTA_MANUAL = 'RESUELTA_MANUAL',
  SUGERIDA_REVISAR = 'SUGERIDA_REVISAR',
  NO_ENCONTRADA = 'NO_ENCONTRADA',
  AGREGADA_MANUAL = 'AGREGADA_MANUAL',
}

export enum OrigenMatch {
  SKU = 'SKU',
  ALIAS_EXACTO = 'ALIAS_EXACTO',
  ALIAS_SIMILITUD = 'ALIAS_SIMILITUD',
  TEXTO_SIMILITUD = 'TEXTO_SIMILITUD',
  ATRIBUTO = 'ATRIBUTO',
  MANUAL = 'MANUAL',
}

export enum TipoEventoCotizacion {
  CREADA = 'CREADA',
  INTERPRETADA = 'INTERPRETADA',
  LINEA_CORREGIDA = 'LINEA_CORREGIDA',
  LINEA_AGREGADA = 'LINEA_AGREGADA',
  LINEA_ELIMINADA = 'LINEA_ELIMINADA',
  PRECIO_SOBRESCRITO = 'PRECIO_SOBRESCRITO',
  ALIAS_APRENDIDO = 'ALIAS_APRENDIDO',
  RECALCULADA = 'RECALCULADA',
  APROBADA = 'APROBADA',
  DOCUMENTO_GENERADO = 'DOCUMENTO_GENERADO',
  ENVIADA = 'ENVIADA',
  MARCADA_GANADA = 'MARCADA_GANADA',
  MARCADA_PERDIDA = 'MARCADA_PERDIDA',
  VENCIDA = 'VENCIDA',
  ANULADA = 'ANULADA',
  DUPLICADA = 'DUPLICADA',
}
